package com.incidentmanagement.util;

public interface Constants {
	
	public static String DECISION_ADMISSION_REJECT = "DECISION_ADMISSION_REJECT";
	public static String STATUS_DE_INCIDENT = "STATUS_DE_INCIDENT";
	public static String TYPE_DE_REFERENCE_EXTERNE = "TYPE_DE_REFERENCE_EXTERNE";
	public static String COMITE_DE_BALE = "COMITE_DE_BALE";
	public static String CODE_ETAT_ACTUAEL_DU_PERT_SUR = "CODE_ETAT_ACTUAEL_DU_PERT_SUR";
	public static String ETATE_DE_LA_PERTE = "ETATE_DE_LA_PERTE";
	public static String CLASSIFICATION_DE_LA_PERTE = "CLASSIFICATION_DE_LA_PERTE";
	public static String NOTATION_DE_LA_PERTE_EN_REPUTATION = "NOTATION_DE_LA_PERTE_EN_REPUTATION";
	public static String AGENCES = "AGENCES";
	public static String UNITE_ORGANISATIONNELLE_CONCERNEE = "UNITE_ORGANISATIONNELLE_CONCERNEE";
	public static String PROCESSUS_CONCERNE = "PROCESSUS_CONCERNE";
	
}
