--------------------------------------------------------
--  File created - Monday-March-20-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DBUSER
--------------------------------------------------------

  CREATE TABLE "JAWAD"."DBUSER" 
   (	"USER_ID" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(50 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"SERVICE_CODE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DBUSER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JAWAD"."DBUSER_PK" ON "JAWAD"."DBUSER" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DBUSER
--------------------------------------------------------

  ALTER TABLE "JAWAD"."DBUSER" ADD CONSTRAINT "DBUSER_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "JAWAD"."DBUSER" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "JAWAD"."DBUSER" MODIFY ("PASSWORD" NOT NULL ENABLE);
 
  ALTER TABLE "JAWAD"."DBUSER" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "JAWAD"."DBUSER" MODIFY ("SERVICE_CODE" NOT NULL ENABLE);
